name: Build Docker image
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get current date
      id: date
      run: echo "date=$(date --utc +%Y%m%d.%H%M)" >> $GITHUB_OUTPUT
    - name: Get sha with 8 chars long
      id: commit_sha
      run: echo "commit_sha=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
    - name: Build and push client image
      uses: docker/build-push-action@v5
      with:
        push: true
        load: false
        platforms: linux/amd64,linux/arm64
        target: release
        tags: |
          ghcr.io/scottaubrey/kasa-energy-monitor:latest
          ghcr.io/scottaubrey/kasa-energy-monitor:${{ github.sha }}
          ghcr.io/scottaubrey/kasa-energy-monitor:master-${{ steps.commit_sha.outputs.commit_sha }}-${{ steps.date.outputs.date }}
